### PR TITLE
Add support for Django 3.0

### PR DESCRIPTION
**Pull request by bobort**
Add support for Django 3.0

I also changed testing since django-setuptests hasn't been updated since Django 1.9.

I'm also new to this.

### CODE REVIEW

**Comment by davidfischer** [comment]
This change looks good. I'm not sure whether the author wants to totally drop support for Python2 (which is not supported by python.org) or Django 1.11 (which is supported through April) but they can make that call. However, adding Python37 and Python38 as well as Django 2.2 to the testing matrix is definitely a good idea.

If the plan is to drop Python2 with the next release, consider [adding `python_requires`](https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires) to `setup.py`. That way Python2 users will continue to download the old version.

**Comment by mpasternak** [comment]
@bobort , please rebase on the latest master (there are conflicts after I merged your previous PR) and I'll merge

**Comment by bobort** [comment]
I'm struggling getting this fixed. I appreciate guidance.

**Comment by mpasternak** [comment]
Merged, thanks

**Comment by mpasternak** [comment]
@bobort Matthew, that's a wonderful piece of work. Thank you for the time taken, thank you for sharing.

**Pull request merged**
