### PR TITLE
Django 2.0 compat!

### PR DESCRIPTION
**Pull request by mpasternak**
As promised in #21

### CODE REVIEW

**Comment by AliLozano** [comment]
It seems to me that everything is fine, I will pull with the master, and next week I do the update in pip.

Thanks.

**Comment by bobort** [comment]
I might be having other problems, but I'm getting an error now in the Django admin.

```
TypeError at /admin/
'bool' object is not callable

58 | <!-- END Header -->
-- | --
{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
{% if title %} &rsaquo; {{ title }}{% endif %}
</div>
{% endblock %}
{% endif %}
 
{% block messages %}
{% if messages %}
<ul class="messagelist">{% for message in messages %}
<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message\|capfirst }}</li>
{% endfor %}</ul>
{% endif %}
{% endblock messages %}
 
<!-- Content -->
<div id="content" class="{% block coltype %}colM{% endblock %}">
{% block pretitle %}{% endblock %}
{% block content_title %}{% if title %}<h1>{{ title }}</h1>{% endif %}{% endblock %}

```

**Comment by mpasternak** [comment]
This was never called in tests. Tests need improvement. I’m on it. 

Wysłane z iPhone'a

**Comment by mpasternak** [comment]
I have created pull request #23 to address the issue. Thank you for reporting @bobort . @AliLozano , that branch's all yours.

**Pull request merged**
